app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:new, :create]
  devise_scope :user do
   resources :users, path: "usuarios", only: [:new, :create], controller: 'registrations'
   resources :users, path: "usuarios", only: [:show, :edit, :update], controller: 'usuarios'
  end

  get '/', to: 'default#home', as: :home
  get '/buscar', to: 'default#search', as: :search

  resources :vertientes
  resources :tipo_documentos
  resources :tipo_institutos
  resources :subcuencas
  resources :statuses
  resources :proyectos
  resources :municipios
  resources :microcuencas

  # Add spanish route names
  resources :investigaciones
  get "/investigaciones/new(.:format)", to: 'investigaciones#new', as: :new_investigacion
  get "/investigaciones/:id/edit(.:format)", to: 'investigaciones#edit', as: :edit_investigacion
  get "/investigaciones/:id(.:format)", to: 'investigaciones#show', as: :investigacion
  patch "/investigaciones/:id(.:format)", to: 'investigaciones#update'
  put "/investigaciones/:id(.:format)", to: 'investigaciones#update'
  delete "/investigaciones/:id(.:format)", to: 'investigaciones#destroy'

  # Add spanish route names
  resources :instituciones
  get "/instituciones/new(.:format)", to: 'instituciones#new', as: :new_institucion
  get "/instituciones/:id/edit(.:format)", to: 'instituciones#edit', as: :edit_institucion
  get "/instituciones/:id(.:format)", to: 'instituciones#show', as: :institucion
  patch "/instituciones/:id(.:format)", to: 'instituciones#update'
  put "/instituciones/:id(.:format)", to: 'instituciones#update'
  delete "/instituciones/:id(.:format)", to: 'instituciones#destroy'

  # Add spanish route names
  resources :facultades
  get "/facultades/new(.:format)", to: 'facultades#new', as: :new_facultad
  get "/facultades/:id/edit(.:format)", to: 'facultades#edit', as: :edit_facultad
  get "/facultades/:id(.:format)", to: 'facultades#show', as: :facultad
  patch "/facultades/:id(.:format)", to: 'facultades#update'
  put "/facultades/:id(.:format)", to: 'facultades#update'
  delete "/facultades/:id(.:format)", to: 'facultades#destroy'

  resources :departamentos
  resources :cuencas
  resources :areas

  # Add asociation route names
  post "/proyectos/:id/asociate_area/(.:format)", to: 'proyectos#asociate_area', as: :proyecto_asociate_area
  post "/investigaciones/:id/asociate_area/(.:format)", to: 'investigaciones#asociate_area', as: :investigacion_asociate_area

  # Add autocomplete route names
  get "/autocomplete/cuencas", to: 'cuencas#autocomplete', as: :cuencas_autocomplete
  get "/autocomplete/subcuencas", to: 'subcuencas#autocomplete', as: :subcuencas_autocomplete
  get "/autocomplete/microcuencas", to: 'microcuencas#autocomplete', as: :microcuencas_autocomplete
  get "/autocomplete/municipios", to: 'municipios#autocomplete', as: :municipios_autocomplete
  get "/autocomplete/facultades", to: 'facultades#autocomplete', as: :facultades_autocomplete

  # Add user routes
  get "/usuarios", to: 'usuarios#index', as: :usuarios
  get "/usuarios/:id(.:format)/enable", to: 'usuarios#enable', as: :enable_usuario
  get "/usuarios/:id(.:format)/disable", to: 'usuarios#disable', as: :disable_usuario
  delete "/usuarios/:id(.:format)", to: 'usuarios#destroy', as: :delete_usuario

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/app/models/vertiente.rb
class Vertiente < ApplicationRecord
  self.table_name = 'vertientes'

  include Auditable

  belongs_to :status, class_name: 'Status', foreign_key: 'id_status'
  has_many :cuencas, class_name: 'Cuenca', foreign_key: 'id_vertiente', inverse_of: :vertiente

  validates :nombre, presence: true
  validates :status, presence: true

  class << self
    def search_entity_class parent = nil
      value = self.name
      value = "#{value}#{self::SEARCH_JOIN_TOKEN}#{parent}" if !parent.blank?
      value
    end

    def search query = nil, opts = {}
      results = self.all
      results = results.where("nombre RLIKE ?", [query]) if !query.blank?
      results.includes(:status)
        .order(:nombre)
    end
  end
end

app/app/controllers/vertientes_controller.rb
class VertientesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_status, only: [:show, :edit, :update, :new, :create]
  before_action :set_vertiente, only: [:show, :edit, :update, :destroy]
  before_action :load_config
  before_action :config_audit, only: [:create, :update, :destroy]

  # GET /vertientes
  # GET /vertientes.json
  def index
    @vertientes = Vertiente.search.page params[:page]
  end

  # GET /vertientes/1
  # GET /vertientes/1.json
  def show
  end

  # GET /vertientes/new
  def new
    @vertiente = Vertiente.new
  end

  # GET /vertientes/1/edit
  def edit
  end

  # POST /vertientes
  # POST /vertientes.json
  def create
    ActiveRecord::Base.transaction do
      @vertiente = Vertiente.new(vertiente_params)

      respond_to do |format|
        if @vertiente.save
          format.html { redirect_to @vertiente, notice: 'La Vertiente se cre&oacute; exitosamente.' }
          format.json { render :show, status: :created, location: @vertiente }
        else
          format.html { render :new }
          format.json { render json: @vertiente.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /vertientes/1
  # PATCH/PUT /vertientes/1.json
  def update
    ActiveRecord::Base.transaction do
      respond_to do |format|
        if @vertiente.update(vertiente_params)
          format.html { redirect_to @vertiente, notice: 'La Vertiente se actualizo correctamente.' }
          format.json { render :show, status: :ok, location: @vertiente }
        else
          format.html { render :edit }
          format.json { render json: @vertiente.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /vertientes/1
  # DELETE /vertientes/1.json
  def destroy
    ActiveRecord::Base.transaction do
      @vertiente.status = Status.find(Status::VALUES[:deleted])
      @vertiente.save validate: false
      respond_to do |format|
        format.html { redirect_to vertientes_url, notice: 'La Vertiente se marco como borrada.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vertiente
      @vertiente = Vertiente.find(params[:id])
    end

    def load_status
      @statuses = Status.user_visible
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vertiente_params
      params.require(:vertiente).permit(:nombre, :id_status)
    end

    def load_config
      @search_type = [Vertiente.search_entity_class]
    end
end

app/app/helpers/vertientes_helper.rb
module VertientesHelper
end

app/app/views/vertientes/_form.html.haml
- form_path = vertiente.id.nil? ? vertientes_path : vertiente_path(vertiente)
= form_with(url: form_path, model: vertiente, local: true) do |form|
  - if vertiente.errors.any?
    #error_explanation.alert.alert-danger{role: 'alert'}
      %h2
        Existen
        = vertiente.errors.count
        = "error".pluralize(vertiente.errors.count, :es)
      %ul
        - vertiente.errors.full_messages.each do |message|
          %li= message

  .row
    .col.col-6.form-group
      = form.label :nombre
      = form.text_field :nombre, id: :vertiente_nombre, class: 'form-control'
    .col.col-6.form-group
      = form.label :id_status, "Estado"
      = form.select :id_status, @statuses.collect{|status| [status.nombre, status.id]}, {}, {id: :vertiente_id_status, class: 'form-control'}
  .row
    .col.actions
      = form.submit "Guardar", class: 'btn btn-primary pull-right'

app/app/views/vertientes/_list.html.haml
- collection ||= []
- param_name ||= :page
- hide_pagination ||= false
- report_mode ||= @report_mode

.row
  - if report_mode
    .col
      %table.table.table-striped
        %thead
          %tr
            %th Nombre
            %th Estado
            %th{:colspan => "3"}
        %tbody
          - collection.each do |vertiente|
            %tr
              %td= vertiente.nombre
              %td= render 'shared/status_beautify', status: vertiente.status
              %td= link_to 'Mostrar', vertiente
              %td= link_to 'Editar', edit_vertiente_path(vertiente)
              %td= link_to 'Borrar', vertiente, method: :delete, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }
  - else
    - collection.each do |vertiente|
      .col.col-xs-12.col-md-4.col-lg-3
        .col.box-item
          = link_to vertiente.nombre, vertiente, class: 'title'
          .data= render 'shared/status_beautify', status: vertiente.status
          .data-id= vertiente.id
          .options
            .aux
              .icon
                %i.fa.fa-ellipsis-v
              .expand
                = link_to 'Mostrar', vertiente
                = link_to 'Editar', edit_vertiente_path(vertiente)
                = link_to 'Borrar', vertiente, class: 'text-danger', method: :delete, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }

- if !hide_pagination
  .row
    .col
      = paginate collection, param_name: param_name

app/app/views/vertientes/edit.html.haml
.container
  .row
    .col.col-9
      %h1 Editar vertiente
    .col.col-3
      = link_to 'Mostrar', vertiente_path(@vertiente), class: 'btn btn-outline-info pull-right'
      = link_to 'Volver', vertientes_path, class: 'btn btn-outline-link pull-right'
  .row
    .col
      = render 'form', vertiente: @vertiente

app/app/views/vertientes/index.html.haml
.container-fluid
  .row
    .col.col-8
      %h1 Vertientes
    .col.col-4
      = link_to 'Nueva vertiente', new_vertiente_path, class:"btn btn-primary pull-right"

  = render 'vertientes/list', collection: @vertientes

app/app/views/vertientes/new.html.haml
.container
  .row
    .col
      %h1 Nueva vertiente
  .row
    .col
      = link_to 'Volver', vertientes_path, class: 'btn btn-ouline-link pull-right'
  .row
    .col
      = render 'form', vertiente: @vertiente

app/app/views/vertientes/show.html.haml
.container
  .row
    .col.col-9
      %h1 Mostrar vertiente
    .col.col-3
      = link_to 'Editar', edit_vertiente_path(@vertiente), class: 'btn btn-outline-primary pull-right'
      = link_to 'Volver', vertientes_path, class: 'btn btn-outline-link pull-right'
  .row
    .col.col-4.font-weight-bold
      ID:
    .col.col-8
      = @vertiente.id
  .row
    .col.col-4.font-weight-bold
      Nombre:
    .col.col-8
      = @vertiente.nombre
  .row
    .col.col-4.font-weight-bold
      Estado
    .col.col-8
      = render 'shared/status_beautify', status: @vertiente.status

  %br/
  %br/

.container-fluid
  .row
    .col.col-8
      %h2 Cuencas
    .col.col-4
      = link_to 'Nueva cuenca', new_cuenca_path, class:"btn btn-primary pull-right"

  = render 'cuencas/list', collection: @vertiente.cuencas, hide_pagination: true