app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:new, :create]
  devise_scope :user do
   resources :users, path: "usuarios", only: [:new, :create], controller: 'registrations'
   resources :users, path: "usuarios", only: [:show, :edit, :update], controller: 'usuarios'
  end

  get '/', to: 'default#home', as: :home
  get '/buscar', to: 'default#search', as: :search

  resources :vertientes
  resources :tipo_documentos
  resources :tipo_institutos
  resources :subcuencas
  resources :statuses
  resources :proyectos
  resources :municipios
  resources :microcuencas

  # Add spanish route names
  resources :investigaciones
  get "/investigaciones/new(.:format)", to: 'investigaciones#new', as: :new_investigacion
  get "/investigaciones/:id/edit(.:format)", to: 'investigaciones#edit', as: :edit_investigacion
  get "/investigaciones/:id(.:format)", to: 'investigaciones#show', as: :investigacion
  patch "/investigaciones/:id(.:format)", to: 'investigaciones#update'
  put "/investigaciones/:id(.:format)", to: 'investigaciones#update'
  delete "/investigaciones/:id(.:format)", to: 'investigaciones#destroy'

  # Add spanish route names
  resources :instituciones
  get "/instituciones/new(.:format)", to: 'instituciones#new', as: :new_institucion
  get "/instituciones/:id/edit(.:format)", to: 'instituciones#edit', as: :edit_institucion
  get "/instituciones/:id(.:format)", to: 'instituciones#show', as: :institucion
  patch "/instituciones/:id(.:format)", to: 'instituciones#update'
  put "/instituciones/:id(.:format)", to: 'instituciones#update'
  delete "/instituciones/:id(.:format)", to: 'instituciones#destroy'

  # Add spanish route names
  resources :facultades
  get "/facultades/new(.:format)", to: 'facultades#new', as: :new_facultad
  get "/facultades/:id/edit(.:format)", to: 'facultades#edit', as: :edit_facultad
  get "/facultades/:id(.:format)", to: 'facultades#show', as: :facultad
  patch "/facultades/:id(.:format)", to: 'facultades#update'
  put "/facultades/:id(.:format)", to: 'facultades#update'
  delete "/facultades/:id(.:format)", to: 'facultades#destroy'

  resources :departamentos
  resources :cuencas
  resources :areas

  # Add asociation route names
  post "/proyectos/:id/asociate_area/(.:format)", to: 'proyectos#asociate_area', as: :proyecto_asociate_area
  post "/investigaciones/:id/asociate_area/(.:format)", to: 'investigaciones#asociate_area', as: :investigacion_asociate_area

  # Add autocomplete route names
  get "/autocomplete/cuencas", to: 'cuencas#autocomplete', as: :cuencas_autocomplete
  get "/autocomplete/subcuencas", to: 'subcuencas#autocomplete', as: :subcuencas_autocomplete
  get "/autocomplete/microcuencas", to: 'microcuencas#autocomplete', as: :microcuencas_autocomplete
  get "/autocomplete/municipios", to: 'municipios#autocomplete', as: :municipios_autocomplete
  get "/autocomplete/facultades", to: 'facultades#autocomplete', as: :facultades_autocomplete

  # Add user routes
  get "/usuarios", to: 'usuarios#index', as: :usuarios
  get "/usuarios/:id(.:format)/enable", to: 'usuarios#enable', as: :enable_usuario
  get "/usuarios/:id(.:format)/disable", to: 'usuarios#disable', as: :disable_usuario
  delete "/usuarios/:id(.:format)", to: 'usuarios#destroy', as: :delete_usuario

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/app/models/subcuenca.rb
class Subcuenca < ApplicationRecord
  self.table_name = 'subcuencas'

  include Auditable

  belongs_to :status, class_name: 'Status', foreign_key: 'id_status'
  belongs_to :cuenca, class_name: 'Cuenca', foreign_key: 'id_cuenca', inverse_of: :subcuencas
  has_many :microcuencas, class_name: 'Microcuenca', foreign_key: 'id_subcuenca', inverse_of: :subcuenca

  validates :nombre, presence: true
  validates :status, presence: true

  class << self
    def search_entity_class parent = nil
      value = self.name
      value = "#{value}#{self::SEARCH_JOIN_TOKEN}#{parent}" if !parent.blank?
      value
    end

    def search query = nil, opts = {}
      parent = opts.delete(:parent)
      results = self.all
      results = results.where(cuenca: parent) if !parent.blank?
      results = results.where("nombre RLIKE ?", [query]) if !query.blank?
      results.includes(:status, :cuenca)
        .order(:nombre)
    end
  end
end

app/app/controllers/subcuencas_controller.rb
class SubcuencasController < ApplicationController
  before_action :authenticate_user!
  before_action :load_status, only: [:show, :edit, :update, :new, :create]
  before_action :set_subcuenca, only: [:show, :edit, :update, :destroy]
  before_action :load_config
  before_action :config_audit, only: [:create, :update, :destroy]

  # GET /subcuencas
  # GET /subcuencas.json
  def index
    @subcuencas = Subcuenca.search.page params[:page]
  end

  # GET /subcuencas/1
  # GET /subcuencas/1.json
  def show
  end

  # GET /subcuencas/new
  def new
    @subcuenca = Subcuenca.new
  end

  # GET /subcuencas/1/edit
  def edit
  end

  # POST /subcuencas
  # POST /subcuencas.json
  def create
    ActiveRecord::Base.transaction do
      @subcuenca = Subcuenca.new(subcuenca_params)

      respond_to do |format|
        if @subcuenca.save
          format.html { redirect_to @subcuenca, notice: 'La Subcuenca se cre&oacute; exitosamente.' }
          format.json { render :show, status: :created, location: @subcuenca }
        else
          format.html { render :new }
          format.json { render json: @subcuenca.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /subcuencas/1
  # PATCH/PUT /subcuencas/1.json
  def update
    ActiveRecord::Base.transaction do
      respond_to do |format|
        if @subcuenca.update(subcuenca_params)
          format.html { redirect_to @subcuenca, notice: 'La Subcuenca se actualizo correctamente.' }
          format.json { render :show, status: :ok, location: @subcuenca }
        else
          format.html { render :edit }
          format.json { render json: @subcuenca.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /subcuencas/1
  # DELETE /subcuencas/1.json
  def destroy
    ActiveRecord::Base.transaction do
      @subcuenca.status = Status.find(Status::VALUES[:deleted])
      @subcuenca.save validate: false
      respond_to do |format|
        format.html { redirect_to subcuencas_url, notice: 'La Subcuenca se marco como borrada.' }
        format.json { head :no_content }
      end
    end
  end

  def autocomplete
    query = params[:term]
    search_expression = convert_to_search_expression query
    limit = APP_CONFIG['autocomplete_limit']
    @collection = []
    unless search_expression.blank?
      @collection = Subcuenca.search(query).limit(limit).order(:nombre)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcuenca
      @subcuenca = Subcuenca.find(params[:id])
    end

    def load_status
      @statuses = Status.user_visible
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcuenca_params
      params.require(:subcuenca).permit(:id_cuenca, :nombre, :id_status)
    end

    def load_config
      @search_type = [Subcuenca.search_entity_class]
    end
end

app/app/helpers/subcuencas_helper.rb
module SubcuencasHelper
end

app/app/views/subcuencas/_form.html.haml
- form_path = subcuenca.id.nil? ? subcuencas_path : subcuenca_path(subcuenca)
= form_with(url: form_path, model: subcuenca, local: true) do |form|
  - if subcuenca.errors.any?
    #error_explanation.alert.alert-danger{role: 'alert'}
      %h2
        Existen
        = subcuenca.errors.count
        = "error".pluralize(subcuenca.errors.count, :es)
      %ul
        - subcuenca.errors.full_messages.each do |message|
          %li= message

  .row
    .col.col-6.form-group
      = form.label :nombre
      = form.text_field :nombre, id: :subcuenca_nombre, class: 'form-control'

    = render 'shared/autocomplete_widget',
      form: form,
      widget_class: 'col col-6 cuenca-field',
      entity: subcuenca.try(:cuenca),
      field: :id_cuenca,
      param_id: :subcuenca_id_cuenca,
      label_text: 'Cuenca'
    .col.col-6.form-group
      = form.label :id_status, "Estado"
      = form.select :id_status, @statuses.collect{|status| [status.nombre, status.id]}, {}, {id: :subcuenca_id_status, class: 'form-control'}
  .row
    .col.actions
      = form.submit "Guardar", class: 'btn btn-primary pull-right'

- content_for :javascript do
  :erb
    <script type="text/javascript">
      (function() {
        // Cuenca autocomplete
        configAutocomplete({
          queryInputSelector: 'form .cuenca-field .query-input',
          valueInputSelector: 'form .cuenca-field .value-input',
          source: '<%= j cuencas_autocomplete_path(format: :json) %>'
        });
      })();
    </script>

app/app/views/subcuencas/_list.html.haml
- collection ||= []
- param_name ||= :page
- hide_pagination ||= false
- report_mode ||= @report_mode

.row
  - if report_mode
    .col
      %table.table.table-striped
        %thead
          %tr
            %th Cuenca
            %th Nombre
            %th Estado
            %th{:colspan => "3"}
        %tbody
          - collection.each do |subcuenca|
            %tr
              %td= subcuenca.nombre
              %td= subcuenca.cuenca.nombre
              %td= render 'shared/status_beautify', status: subcuenca.status
              %td= link_to 'Mostrar', subcuenca
              %td= link_to 'Editar', edit_subcuenca_path(subcuenca)
              %td= link_to 'Borrar', subcuenca, method: :delete, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }
  - else
    - collection.each do |subcuenca|
      .col.col-xs-12.col-md-4.col-lg-3
        .col.box-item
          = link_to subcuenca.nombre, subcuenca, class: 'title'
          .data= subcuenca.cuenca.nombre
          .data= render 'shared/status_beautify', status: subcuenca.status
          .data-id= subcuenca.id
          .options
            .aux
              .icon
                %i.fa.fa-ellipsis-v
              .expand
                = link_to 'Mostrar', subcuenca
                = link_to 'Editar', edit_subcuenca_path(subcuenca)
                = link_to 'Borrar', subcuenca, class: 'text-danger', method: :delete, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }

- if !hide_pagination
  .row
    .col
      = paginate collection, param_name: param_name

app/app/views/subcuencas/edit.html.haml
.container
  .row
    .col.col-9
      %h1 Editar subcuenca
    .col.col-3
      = link_to 'Mostrar', subcuenca_path(@subcuenca), class: 'btn btn-outline-info pull-right'
      = link_to 'Volver', subcuencas_path, class: 'btn btn-outline-link pull-right'
  .row
    .col
      = render 'form', subcuenca: @subcuenca

app/app/views/subcuencas/index.html.haml
.container-fluid
  .row
    .col.col-8
      %h1 Subcuencas
    .col.col-4
      = link_to 'Nueva subcuenca', new_subcuenca_path, class:"btn btn-primary pull-right"

  = render 'subcuencas/list', collection: @subcuencas

app/app/views/subcuencas/new.html.haml
.container
  .row
    .col
      %h1 Nueva subcuenca
  .row
    .col
      = link_to 'Volver', subcuencas_path, class: 'btn btn-ouline-link pull-right'
  .row
    .col
      = render 'form', subcuenca: @subcuenca

app/app/views/subcuencas/show.html.haml
.container
  .row
    .col.col-9
      %h1 Mostrar subcuenca
    .col.col-3
      = link_to 'Editar', edit_subcuenca_path(@subcuenca), class: 'btn btn-outline-primary pull-right'
      = link_to 'Volver', subcuencas_path, class: 'btn btn-outline-link pull-right'
  .row
    .col.col-4.font-weight-bold
      ID:
    .col.col-8
      = @subcuenca.id
  .row
    .col.col-4.font-weight-bold
      Nombre:
    .col.col-8
      = @subcuenca.nombre
  .row
    .col.col-4.font-weight-bold
      Vertiente / Cuenca:
    .col.col-8
      = @subcuenca.try(:cuenca).try(:vertiente).try(:nombre)
      = "/"
      = @subcuenca.try(:cuenca).try(:nombre)
  .row
    .col.col-4.font-weight-bold
      Estado
    .col.col-8
      = render 'shared/status_beautify', status: @subcuenca.status

  %br/
  %br/
.container-fluid
  .row
    .col.col-8
      %h2 Microcuencas
    .col.col-4
      = link_to 'Nueva microcuenca', new_microcuenca_path, class:"btn btn-primary pull-right"

  = render 'microcuencas/list', collection: @subcuenca.microcuencas, hide_pagination: true