app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:new, :create]
  devise_scope :user do
   resources :users, path: "usuarios", only: [:new, :create], controller: 'registrations'
   resources :users, path: "usuarios", only: [:show, :edit, :update], controller: 'usuarios'
  end

  get '/', to: 'default#home', as: :home
  get '/buscar', to: 'default#search', as: :search

  resources :vertientes
  resources :tipo_documentos
  resources :tipo_institutos
  resources :subcuencas
  resources :statuses
  resources :proyectos
  resources :municipios
  resources :microcuencas

  # Add spanish route names
  resources :investigaciones
  get "/investigaciones/new(.:format)", to: 'investigaciones#new', as: :new_investigacion
  get "/investigaciones/:id/edit(.:format)", to: 'investigaciones#edit', as: :edit_investigacion
  get "/investigaciones/:id(.:format)", to: 'investigaciones#show', as: :investigacion
  patch "/investigaciones/:id(.:format)", to: 'investigaciones#update'
  put "/investigaciones/:id(.:format)", to: 'investigaciones#update'
  delete "/investigaciones/:id(.:format)", to: 'investigaciones#destroy'

  # Add spanish route names
  resources :instituciones
  get "/instituciones/new(.:format)", to: 'instituciones#new', as: :new_institucion
  get "/instituciones/:id/edit(.:format)", to: 'instituciones#edit', as: :edit_institucion
  get "/instituciones/:id(.:format)", to: 'instituciones#show', as: :institucion
  patch "/instituciones/:id(.:format)", to: 'instituciones#update'
  put "/instituciones/:id(.:format)", to: 'instituciones#update'
  delete "/instituciones/:id(.:format)", to: 'instituciones#destroy'

  # Add spanish route names
  resources :facultades
  get "/facultades/new(.:format)", to: 'facultades#new', as: :new_facultad
  get "/facultades/:id/edit(.:format)", to: 'facultades#edit', as: :edit_facultad
  get "/facultades/:id(.:format)", to: 'facultades#show', as: :facultad
  patch "/facultades/:id(.:format)", to: 'facultades#update'
  put "/facultades/:id(.:format)", to: 'facultades#update'
  delete "/facultades/:id(.:format)", to: 'facultades#destroy'

  resources :departamentos
  resources :cuencas
  resources :areas

  # Add asociation route names
  post "/proyectos/:id/asociate_area/(.:format)", to: 'proyectos#asociate_area', as: :proyecto_asociate_area
  post "/investigaciones/:id/asociate_area/(.:format)", to: 'investigaciones#asociate_area', as: :investigacion_asociate_area

  # Add autocomplete route names
  get "/autocomplete/cuencas", to: 'cuencas#autocomplete', as: :cuencas_autocomplete
  get "/autocomplete/subcuencas", to: 'subcuencas#autocomplete', as: :subcuencas_autocomplete
  get "/autocomplete/microcuencas", to: 'microcuencas#autocomplete', as: :microcuencas_autocomplete
  get "/autocomplete/municipios", to: 'municipios#autocomplete', as: :municipios_autocomplete
  get "/autocomplete/facultades", to: 'facultades#autocomplete', as: :facultades_autocomplete

  # Add user routes
  get "/usuarios", to: 'usuarios#index', as: :usuarios
  get "/usuarios/:id(.:format)/enable", to: 'usuarios#enable', as: :enable_usuario
  get "/usuarios/:id(.:format)/disable", to: 'usuarios#disable', as: :disable_usuario
  delete "/usuarios/:id(.:format)", to: 'usuarios#destroy', as: :delete_usuario

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/app/controllers/usuarios_controller.rb
require 'cgi'

class UsuariosController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only_access, except: [:edit, :update]
  before_action :load_status, only: [:show, :edit, :update]
  before_action :set_usuario, only: [:show, :edit, :update, :enable, :disable, :destroy]
  before_action :validate_current_user_access, only: [:edit, :update]
  before_action :load_config
  before_action :config_audit, only: [:update, :destroy, :enable,:disable]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @users = User.search.page params[:page]
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/1/edit
  def edit
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    ActiveRecord::Base.transaction do
      respond_to do |format|
        validate_current_password
        @user.assign_attributes(usuario_params)
        if @user.errors.blank? && @user.update(usuario_params)
          format.html { redirect_to @user, notice: 'El Usuario se actualizo correctamente.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def enable
    return if current_user.id == @user.id
    ActiveRecord::Base.transaction do
      @user.status = Status.find(Status::VALUES[:active])
      @user.save validate: false
      respond_to do |format|
        format.html { redirect_to usuarios_url, notice: "El usuario #{@user.email} se habilito." }
        format.json { head :no_content }
      end
    end
  end

  def disable
    return if current_user.id == @user.id
    ActiveRecord::Base.transaction do
      @user.status = Status.find(Status::VALUES[:inactive])
      @user.save validate: false
      respond_to do |format|
        format.html { redirect_to usuarios_url, notice: "El usuario #{@user.email} se desabilito." }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    return if current_user.id == @user.id
    ActiveRecord::Base.transaction do
      @user.status = Status.find(Status::VALUES[:deleted])
      @user.save validate: false
      respond_to do |format|
        format.html { redirect_to usuarios_url, notice: "El usuario #{@user.email} se marco como borrado." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @user = User.find(params[:id])
    end

    def load_status
      @statuses = Status.user_visible
    end

    def would_change_password
      password_params = params.require(:user).permit(:password, :password_confirmation)
      !password_params[:password].blank? || !password_params[:password_confirmation].blank?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      allowed_params = [:nombre, :telefono]
      if current_user.admin?
        allowed_params << :email
        allowed_params << :role
        allowed_params << :id_status
      end
      if would_change_password
        allowed_params << :password
        allowed_params << :password_confirmation
      end
      params.require(:user).permit(allowed_params)
    end

    def load_config
      @search_type = [User.search_entity_class]
    end

    def validate_current_user_access
      return if current_user.admin? || current_user.id == @user.id
      respond_to do |format|
        format.html { redirect_to root_url }
        format.json { head :no_content }
      end
    end

    def validate_current_password
      return if current_user.id != @user.id
      current_password = params.require(:user).permit(:current_password)[:current_password]
      return if @user.valid_password? current_password
      @user.errors.add('Contrase&ntilde;a actual', 'no es valid.')
    end
end

app/app/views/usuarios/_form.html.haml
- is_current_user = current_user.id == @user.id

- form_path = user.id.nil? ? usuarios_path : user_path(user)
= form_with(url: form_path, model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation.alert.alert-danger{role: 'alert'}
      %h2
        Existen
        = user.errors.count
        = "error".pluralize(user.errors.count, :es)
      %ul
        - user.errors.full_messages.each do |message|
          %li= message.html_safe

  .row
    - if current_user.admin?
      .col.col-6.form-group
        = form.label :email
        = form.text_field :email, id: :user_email, class: 'form-control'

    .col.col-6.form-group
      = form.label :nombre
      = form.text_field :nombre, id: :user_nombre, class: 'form-control'

    .col.col-6.form-group
      = form.label :password, 'Nueva Contrase&ntilde;a'.html_safe
      = form.password_field :password, id: :user_password, class: 'form-control'
    .col.col-6.form-group
      = form.label :password_confirmation, 'Confirmar Contrase&ntilde;a'.html_safe
      = form.password_field :password_confirmation, id: :user_password_confirmation, class: 'form-control'

    .col.col-6.form-group
      = form.label :telefono, "Tel&eacute;fono".html_safe
      = form.text_field :telefono, id: :user_telefono, class: 'form-control'

    - if is_current_user
      .col.col-6.form-group
        = form.label :current_password, 'Contrase&ntilde;a Actual'.html_safe
        = form.password_field :current_password, id: :user_current_password, class: 'form-control'

    - if current_user.admin?
      .col.col-6.form-group
        = form.label :role, "Rol del Usuario"
        = form.select :role, User::ROLES.collect{|role| [User.role_label(role), role]}, {}, {id: :user_role, class: 'form-control'}

      .col.col-6.form-group
        = form.label :id_status, "Estado"
        = form.select :id_status, @statuses.collect{|status| [status.nombre, status.id]}, {}, {id: :user_id_status, class: 'form-control'}
  .row
    .col.actions
      = form.submit "Guardar", class: 'btn btn-primary pull-right'

app/app/views/usuarios/_list.html.haml
- collection ||= []
- param_name ||= :page
- hide_pagination ||= false
- report_mode ||= @report_mode

.row
  - if report_mode
    .col
      %table.table.table-striped
        %thead
          %tr
            %th Correo electr&oacute;nico
            %th Role
            %th Estado
            %th{:colspan => "5"}
        %tbody
          - collection.each do |user|
            %tr
              %td= user.nombre
              %td= user.email
              %td= user.role_label
              %td= render 'shared/status_beautify', status: user.status
              %td= link_to 'Mostrar', user_path(user)
              %td= link_to 'Editar', edit_user_path(user)
              %td
                - if user.status.visible?
                  = link_to 'Desabilitar', usuario_disable_path, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }
                - else
                  = link_to 'Habilitar', usuario_enable_path, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }
              %td= link_to 'Borrar', delete_usuario_path(id: user.id), data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }
  - else
    - collection.each do |user|
      .col.col-xs-12.col-md-4.col-lg-3
        .col.box-item
          .title= user.nombre.blank? ? 'N/A' : user.nombre
          .data= user.email
          .data= user.role_label
          .data= render 'shared/status_beautify', status: user.status
          .data-id= user.id
          .options
            .aux
              .icon
                %i.fa.fa-ellipsis-v
              .expand
                = link_to 'Mostrar', user_path(user)
                = link_to 'Editar', edit_user_path(user)
                - if current_user.id != user.id
                  - if user.status.visible?
                    = link_to 'Desabilitar', disable_usuario_path(id: user.id), data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }
                  - else
                    = link_to 'Habilitar', enable_usuario_path(id: user.id), data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }
                  = link_to 'Borrar', delete_usuario_path(id: user.id), method: :delete, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }

- if !hide_pagination
  .row
    .col
      = paginate collection, param_name: param_name

app/app/views/usuarios/edit.html.haml
- is_current_user = current_user.id == @user.id
.container
  .row
    .col.col-9
      %h1
        Editar
        - if is_current_user
          mi usuario
        - else
          usuario
    .col.col-3
      = link_to 'Mostrar', user_path(@user), class: 'btn btn-outline-info pull-right'
      - if !current_user.admin? && is_current_user
        = link_to 'Volver', home_path, class: 'btn btn-outline-link pull-right'
      - else
        = link_to 'Volver', usuarios_path, class: 'btn btn-outline-link pull-right'
  .row
    .col
      = render 'form', user: @user

app/app/views/usuarios/index.html.haml
.container-fluid
  .row
    .col.col-8
      %h1 Usuarios
    .col.col-4
      = link_to 'Nuevo usuario', new_user_path, class:"btn btn-primary pull-right"

  = render 'usuarios/list', collection: @users

app/app/views/usuarios/show.html.haml
- is_current_user = current_user.id == @user.id
.container
  .row
    .col.col-9
      %h1
        Mostrar
        - if is_current_user
          mi usuario
        - else
          usuario
    .col.col-3
      = link_to 'Editar', edit_user_path(@user), class: 'btn btn-outline-primary pull-right'
      - if !current_user.admin? && is_current_user
        = link_to 'Volver', home_path, class: 'btn btn-outline-link pull-right'
      - else
        = link_to 'Volver', usuarios_path, class: 'btn btn-outline-link pull-right'
  .row
    .col.col-4.font-weight-bold
      ID:
    .col.col-8
      = @user.id
  .row
    .col.col-4.font-weight-bold
      Nombre:
    .col.col-8
      = @user.nombre

  .row
    .col.col-4.font-weight-bold
      Correo electr&oacute;nico
    .col.col-8
      = render 'shared/email_beautify', item: @user
  .row
    .col.col-4.font-weight-bold
      Tel&eacute;fono
    .col.col-8
      = @user.telefono
  .row
    .col.col-4.font-weight-bold
      Rol del Usuario
    .col.col-8
      = @user.role_label
  .row
    .col.col-4.font-weight-bold
      Estado
    .col.col-8
      = render 'shared/status_beautify', status: @user.status