app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:new, :create]
  devise_scope :user do
   resources :users, path: "usuarios", only: [:new, :create], controller: 'registrations'
   resources :users, path: "usuarios", only: [:show, :edit, :update], controller: 'usuarios'
  end

  get '/', to: 'default#home', as: :home
  get '/buscar', to: 'default#search', as: :search

  resources :vertientes
  resources :tipo_documentos
  resources :tipo_institutos
  resources :subcuencas
  resources :statuses
  resources :proyectos
  resources :municipios
  resources :microcuencas

  # Add spanish route names
  resources :investigaciones
  get "/investigaciones/new(.:format)", to: 'investigaciones#new', as: :new_investigacion
  get "/investigaciones/:id/edit(.:format)", to: 'investigaciones#edit', as: :edit_investigacion
  get "/investigaciones/:id(.:format)", to: 'investigaciones#show', as: :investigacion
  patch "/investigaciones/:id(.:format)", to: 'investigaciones#update'
  put "/investigaciones/:id(.:format)", to: 'investigaciones#update'
  delete "/investigaciones/:id(.:format)", to: 'investigaciones#destroy'

  # Add spanish route names
  resources :instituciones
  get "/instituciones/new(.:format)", to: 'instituciones#new', as: :new_institucion
  get "/instituciones/:id/edit(.:format)", to: 'instituciones#edit', as: :edit_institucion
  get "/instituciones/:id(.:format)", to: 'instituciones#show', as: :institucion
  patch "/instituciones/:id(.:format)", to: 'instituciones#update'
  put "/instituciones/:id(.:format)", to: 'instituciones#update'
  delete "/instituciones/:id(.:format)", to: 'instituciones#destroy'

  # Add spanish route names
  resources :facultades
  get "/facultades/new(.:format)", to: 'facultades#new', as: :new_facultad
  get "/facultades/:id/edit(.:format)", to: 'facultades#edit', as: :edit_facultad
  get "/facultades/:id(.:format)", to: 'facultades#show', as: :facultad
  patch "/facultades/:id(.:format)", to: 'facultades#update'
  put "/facultades/:id(.:format)", to: 'facultades#update'
  delete "/facultades/:id(.:format)", to: 'facultades#destroy'

  resources :departamentos
  resources :cuencas
  resources :areas

  # Add asociation route names
  post "/proyectos/:id/asociate_area/(.:format)", to: 'proyectos#asociate_area', as: :proyecto_asociate_area
  post "/investigaciones/:id/asociate_area/(.:format)", to: 'investigaciones#asociate_area', as: :investigacion_asociate_area

  # Add autocomplete route names
  get "/autocomplete/cuencas", to: 'cuencas#autocomplete', as: :cuencas_autocomplete
  get "/autocomplete/subcuencas", to: 'subcuencas#autocomplete', as: :subcuencas_autocomplete
  get "/autocomplete/microcuencas", to: 'microcuencas#autocomplete', as: :microcuencas_autocomplete
  get "/autocomplete/municipios", to: 'municipios#autocomplete', as: :municipios_autocomplete
  get "/autocomplete/facultades", to: 'facultades#autocomplete', as: :facultades_autocomplete

  # Add user routes
  get "/usuarios", to: 'usuarios#index', as: :usuarios
  get "/usuarios/:id(.:format)/enable", to: 'usuarios#enable', as: :enable_usuario
  get "/usuarios/:id(.:format)/disable", to: 'usuarios#disable', as: :disable_usuario
  delete "/usuarios/:id(.:format)", to: 'usuarios#destroy', as: :delete_usuario

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/app/models/proyecto.rb
class Proyecto < ApplicationRecord
  self.table_name = 'proyecto_programa'

  include Auditable

  belongs_to :status, class_name: 'Status', foreign_key: 'id_status'
  belongs_to :facultad, class_name: 'Facultad', foreign_key: 'id_instituto', inverse_of: :proyectos
  has_and_belongs_to_many :areas,
      class_name: "Area",
      foreign_key: "id_proyecto",
      association_foreign_key: "id_area",
      join_table: 'proyecto_area',
      inverse_of: :proyectos

  validates :nombre, presence: true
  validates :status, presence: true

  class << self
    def search_entity_class parent = nil
      value = self.name
      value = "#{value}#{self::SEARCH_JOIN_TOKEN}#{parent}" if !parent.blank?
      value
    end

    def search query = nil, opts = {}
      parent = opts.delete(:parent)
      results = self.all
      results = results.where(facultad: parent) if !parent.blank?
      results = results.where("nombre RLIKE ?", [query]) if !query.blank?
      results.includes(:status, :facultad)
        .order(:nombre)
    end
  end
end

app/app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :authenticate_user!
  before_action :load_status, only: [:show, :edit, :update, :new, :create]
  before_action :load_facultad, only: [:edit, :update, :new, :create]
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy, :asociate_area]
  before_action :load_area, only: [:show]
  before_action :load_config
  before_action :config_audit, only: [:create, :update, :destroy, :asociate_area]

  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.search.page params[:page]
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    ActiveRecord::Base.transaction do
      @proyecto = Proyecto.new(proyecto_params)

      respond_to do |format|
        if @proyecto.save
          format.html { redirect_to @proyecto, notice: 'Proyecto programa se cre&oacute; exitosamente.' }
          format.json { render :show, status: :created, location: @proyecto }
        else
          format.html { render :new }
          format.json { render json: @proyecto.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    ActiveRecord::Base.transaction do
      respond_to do |format|
        if @proyecto.update(proyecto_params)
          format.html { redirect_to @proyecto, notice: 'Proyecto programa se actualizo correctamente.' }
          format.json { render :show, status: :ok, location: @proyecto }
        else
          format.html { render :edit }
          format.json { render json: @proyecto.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    ActiveRecord::Base.transaction do
      @proyecto.status = Status.find(Status::VALUES[:deleted])
      @proyecto.save validate: false
      respond_to do |format|
        format.html { redirect_to proyectos_url, notice: 'Proyecto programa se marco como borrado.' }
        format.json { head :no_content }
      end
    end
  end

  def asociate_area
    ActiveRecord::Base.transaction do
      form_params = proyecto_area_params
      area_id = form_params[:id_area]
      @area = Area.find(area_id)
      existing_asociation = ProyectoArea.where(id_area: area_id, id_proyecto: @proyecto.id)

      respond_to do |format|
        if existing_asociation.blank?
          ProyectoArea.create id_proyecto: @proyecto.id, id_area: area_id
          format.html { redirect_to @proyecto, notice: "Se agrego el area \"#{@area.nombre}\" exitosamente." }
          format.json { render :show, status: :ok, location: @proyecto }
        else
          existing_asociation.destroy_all
          format.html { redirect_to @proyecto, notice: "Se quito el area \"#{@area.nombre}\" exitosamente." }
          format.json { render :show, status: :ok, location: @proyecto }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    def load_status
      @statuses = Status.user_visible
    end

    def load_facultad
      @facultades = Facultad.all
    end

    def load_area
      @areas = Area.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyecto_params
      params.require(:proyecto).permit(:id_instituto, :nombre, :descripcion, :id_status)
    end

    def proyecto_area_params
      params.require(:proyecto_area).permit(:id_area)
    end

    def load_config
      @search_type = [Proyecto.search_entity_class]
    end
end

app/app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/app/views/proyectos/_area_asociation_form.html.haml
- proyecto ||= @proyecto
- areas ||= @areas
- form_path = proyecto_asociate_area_path id: proyecto.id
= form_with(url: form_path, local: true) do |form|
  .row
    .col.col-8.form-group
      = form.label :id_area, "&Aacute;rea de estudio".html_safe
      = form.select :id_area, areas.collect{|i| [i.nombre, i.id]}, {}, {id: :proyecto_area_id_area, name: 'proyecto_area[id_area]', class: 'form-control'}
    .col.col-4.actions
      %br/
      = form.submit "Agregar o quitar &aacute;rea de estudio".html_safe, class: 'btn btn-primary pull-right'

app/app/views/proyectos/_form.html.haml
- form_path = proyecto.id.nil? ? proyectos_path : proyecto_path(proyecto)
= form_with(url: form_path, model: proyecto, local: true) do |form|
  - if proyecto.errors.any?
    #error_explanation.alert.alert-danger{role: 'alert'}
      %h2
        Existen
        = proyecto.errors.count
        = "error".pluralize(proyecto.errors.count, :es)
      %ul
        - proyecto.errors.full_messages.each do |message|
          %li= message

  .row
    .col.col-6.form-group
      = form.label :nombre
      = form.text_field :nombre, id: :proyecto_nombre, class: 'form-control'
    = render 'shared/autocomplete_widget',
      form: form,
      widget_class: 'col col-6 facultad-field',
      entity: proyecto.facultad,
      field: :id_instituto,
      param_id: :proyecto_id_instituto,
      label_text: 'Facultad o instituto'
    .col.col-12.form-group
      = form.label :descripcion, "Descripci&oacute;n".html_safe
      = form.text_area :descripcion, id: :proyecto_descripcion, class: 'form-control'
    .col.col-6.form-group
      = form.label :id_status, "Estado"
      = form.select :id_status, @statuses.collect{|status| [status.nombre, status.id]}, {}, {id: :proyecto_id_status, class: 'form-control'}
  .row
    .col.actions
      = form.submit "Guardar", class: 'btn btn-primary pull-right'

- content_for :javascript do
  :erb
    <script type="text/javascript">
      (function() {
        // Facultad autocomplete
        configAutocomplete({
          queryInputSelector: 'form .facultad-field .query-input',
          valueInputSelector: 'form .facultad-field .value-input',
          source: '<%= j facultades_autocomplete_path(format: :json) %>'
        });
      })();
    </script>

app/app/views/proyectos/_list.html.haml
- collection ||= []
- param_name ||= :page
- hide_pagination ||= false
- report_mode ||= @report_mode

.row
  - if report_mode
    .col
      %table.table.table-striped
        %thead
          %tr
            %th Facultad
            %th Nombre
            %th Descripci&oacute;n
            %th Estado
            %th{:colspan => "3"}
        %tbody
          - collection.each do |proyecto|
            %tr
              %td= proyecto.nombre
              %td= proyecto.facultad.nil? ? 'N/A' : proyecto.facultad.nombre
              %td= proyecto.descripcion
              %td= render 'shared/status_beautify', status: proyecto.status
              %td= link_to 'Mostrar', proyecto
              %td= link_to 'Editar', edit_proyecto_path(proyecto)
              %td= link_to 'Borrar', proyecto, method: :delete, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }
  - else
    - collection.each do |proyecto|
      .col.col-xs-12.col-md-4.col-lg-3
        .col.box-item
          = link_to proyecto.nombre, proyecto, class: 'title'
          .data= proyecto.facultad.nil? ? 'N/A' : proyecto.facultad.nombre
          .data= render 'shared/area_collection_beautify', collection: proyecto.areas
          .data= render 'shared/status_beautify', status: proyecto.status
          .data-id= proyecto.id
          .options
            .aux
              .icon
                %i.fa.fa-ellipsis-v
              .expand
                = link_to 'Mostrar', proyecto
                = link_to 'Editar', edit_proyecto_path(proyecto)
                = link_to 'Borrar', proyecto, class: 'text-danger', method: :delete, data: { confirm: '&iquest;Est&aacute; seguro?'.html_safe }

- if !hide_pagination
  .row
    .col
      = paginate collection, param_name: param_name

app/app/views/proyectos/edit.html.haml
.container
  .row
    .col.col-9
      %h1 Editar proyecto o programa
    .col.col-3
      = link_to 'Mostrar', proyecto_path(@proyecto), class: 'btn btn-outline-info pull-right'
      = link_to 'Volver', proyectos_path, class: 'btn btn-outline-link pull-right'
  .row
    .col
      = render 'form', proyecto: @proyecto

app/app/views/proyectos/index.html.haml
.container-fluid
  .row
    .col.col-8
      %h1 Proyectos y programas
    .col.col-4
      = link_to 'Nuevo proyecto o programa', new_proyecto_path, class:"btn btn-primary pull-right"

  = render 'proyectos/list', collection: @proyectos

app/app/views/proyectos/new.html.haml
.container
  .row
    .col
      %h1 Nuevo proyecto o programa
  .row
    .col
      = link_to 'Volver', proyectos_path, class: 'btn btn-ouline-link pull-right'
  .row
    .col
      = render 'form', proyecto: @proyecto

app/app/views/proyectos/show.html.haml
.container
  .row
    .col.col-9
      %h1 Mostrar proyecto o programa
    .col.col-3
      = link_to 'Editar', edit_proyecto_path(@proyecto), class: 'btn btn-outline-primary pull-right'
      = link_to 'Volver', proyectos_path, class: 'btn btn-outline-link pull-right'
  .row
    .col.col-4.font-weight-bold
      ID:
    .col.col-8
      = @proyecto.id
  .row
    .col.col-4.font-weight-bold
      Nombre:
    .col.col-8
      = @proyecto.nombre
  .row
    .col.col-4.font-weight-bold
      Facultad / instituto:
    .col.col-8
      = @proyecto.facultad.try(:nombre)
  .row
    .col.col-4.font-weight-bold
      Instituci&oacute;n:
    .col.col-8
      = @proyecto.facultad.try(:institucion).try(:nombre)
  .row
    .col.col-4.font-weight-bold
      Descripci&oacute;n:
    .col.col-8
      = @proyecto.descripcion
  .row
    .col.col-4.font-weight-bold
      Estado
    .col.col-8
      = render 'shared/status_beautify', status: @proyecto.status

  %br/

.container
  .row
    .col.col-12
      = render 'proyectos/area_asociation_form'
  %br/
  %br/
.container-fluid
  .row
    .col.col-12
      %h2 &Aacute;reas de estudio del proyecto o programa
  = render 'areas/list', collection: @proyecto.areas, hide_pagination: true